import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar/navbar'
import LoginModal from '@/app/Components/modals/LoginModal'
import SignupModal from './Components/modals/signupModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Airbnb Clone ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const content = <p> Hi here</p>
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="pt-32">{children} </div>
        <LoginModal />
        <SignupModal />
      </body>
    </html>
  )
}
